### ISSUE TITLE
Source Code Improvements

### ISSUE THREAD

**Issue by TheKodeToad** [Sol-Client/client#101]
## Problem
The imports are quite long and the source files should really have licence headers.

## Solution
Let the IDE do it for me.

![image](https://user-images.githubusercontent.com/57493648/194749819-4fc49f22-be65-4181-9ea8-685dc553f7cc.png)
and
![image](https://user-images.githubusercontent.com/57493648/194749892-389376ca-dddd-4138-85d1-811fe4c2370e.png)
(I previously had this set to 1000000000 because there's no setting to turn it off in JetBrains - for quite good reason I now realise)

For license,

![image](https://user-images.githubusercontent.com/57493648/194750020-c0ebc960-171e-4d85-86d4-a18825e86e98.png)

**Comment by moehreag** [comment]
The task of adding a license header could be automated by Quilt's licenser gradle plugin.
Usage example: https://github.com/LambdAurora/LambDynamicLights/blob/1.19/build.gradle
