### ISSUE TITLE
Game instantly crashes on startup

### ISSUE THREAD

**Issue by BigBoiMan123** [Sol-Client/Client#103]
## Description (please fill in)
The game will instantly crash on startup. I am using the AppImage launcher. 
## Steps to Reproduce
1. Download and open the latest AppImage launcher. 
2. Press 'Play'
3. Game crashes after a few seconds
## Details
Running Sol Client v1.8.8 with OptiFine 1.8.9 HD U M5 on Void GNU/Linux, kernel 6.0.1.
## Logs/Crash Report

[latest.txt](https://github.com/Sol-Client/Client/files/9811244/latest.txt)

**Comment by TheKodeToad** [comment]
Maybe try without OptiFine?
