### ISSUE TITLE
Just use Quilt & Fabric!

### ISSUE THREAD

**Issue by TheKodeToad** [Sol-Client/Client#119]
(updated title as it seems the latest quilt works better with 1.8)

## Problem
It's not nice having to reimplement stuff when there's an obvious alternative.

## Solution
Using Quilt loader - turning this into a Quilt mod.

## Alternative Solutions
Forge 🙅‍♀️
Fabric - maybe could be used until Quilt is more stable.

## Additional context
It will make more sense when multiversion maybe is a thing

**Comment by RaptaG** [comment]
Wow that's a nice idea

**Comment by RaptaG** [comment]
No OptiFine tho, but anyway OF sucks so..

**Comment by notiriscent** [comment]
> No OptiFine tho, but anyway OF sucks so.. @RaptaG 

[insert a fabric alternative of OF], eh?

**Comment by moehreag** [comment]
> > No OptiFine tho, but anyway OF sucks so.. @RaptaG
> 
> [insert a fabric alternative of OF], eh?

<http://lambdaurora.dev/optifine_alternatives>

**Comment by TheKodeToad** [comment]
Until multiversion I'm mainly focusing on 1.8, so OptiFine is the only viable option (I know of) besides SaltLib. On 1.8 OptiFabric can be used if turned on. On 1.19, there can be an option to choose between Sodium or OptiFabric.

The advantage to using a mod loader is people could also add additional mods like Phosphor or Starlight, or their own custom fork or build of Sodium. On 1.8 there's less benifit to this though, and Replay Mod only runs on legacy Forge versions.

**Comment by RaptaG** [comment]
Do will OF work on 1.8 with Legacy Fabric and OptiFabric on Sol?

**Comment by TheKodeToad** [comment]
> Do will OF work on 1.8 with Legacy Fabric and OptiFabric on Sol?

Yes!
https://github.com/RedLime/OptiFabric-Pre1.14
It doesn't require legacy-fabric-api either.

**Comment by moehreag** [comment]
> > Do will OF work on 1.8 with Legacy Fabric and OptiFabric on Sol?
> 
> Yes! https://github.com/RedLime/OptiFabric-Pre1.14 It doesn't require legacy-fabric-api either.

The mixins will still break when using any mod with quilt-loader on 1.8.9 though

**Comment by TheKodeToad** [comment]
Maybe this *should* only be used with 1.19 then. It just feels awkward to write all of the class transformation logic.

Btw, my earlier comment wasn't worded properly - I've edited it.

**Comment by TheKodeToad** [comment]
It is getting silly to have to create a fake mod json just so the access wideners are picked up...

**Comment by RaptaG** [comment]
Will you make Sol a mod in 1.9.0 or 2.0.0 @TheKodeToad?

**Comment by TheKodeToad** [comment]
I've not decided yet.

**Comment by RaptaG** [comment]
Alright

**Comment by RaptaG** [comment]
Why not Fabric? (Plus I think Legacy Quilt doesn't exist yet)

**Comment by TheKodeToad** [comment]
Quilt generally works with more mods as it has O.K. fabric compat (not perfect).
Legacy Quilt kind of exists thanks to moehreag's https://github.com/moehreag/lfapiQuiltCompat.

**Comment by RaptaG** [comment]
I don't suggest Quilt right now only because it's in beta. Other than that it seems to be a good, modular mod loader.

**Comment by TheKodeToad** [comment]
Hmm, maybe there could be options for both.

**Comment by TheKodeToad** [comment]
I've thought about it but I don't think this would work well! Mods would be broken and tbh i mainly wanted to use it to avoid boilerplate.

**Comment by RaptaG** [comment]
💀

**Comment by TheKodeToad** [comment]
It would be confusing having multiple mod menus and would probably give mod devs a headache :p

**Comment by RaptaG** [comment]
Either way just release 2.0.0 🙏🏽

**Comment by TheKodeToad** [comment]
It probably will be 2.0.0 by now with the number of changes :P (I initially planned it to be 1.9.0)

**Comment by RaptaG** [comment]
👍🏽
