### ISSUE TITLE
build doesnt work

### ISSUE THREAD

**Issue by ItzPrism** [Sol-Client/Client#134]
## Describe the bug
the client doesnt want to build

## Steps to Reproduce
1. open terminal
2. cd into client directory
3. run './gradlew build'
4. then you should get a error

## Expected behavior
it always says build failed with this: FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 726ms
1 actionable task: 1 executed

## Environment
I run Java 8, Gradle 7.1, System is PopOS with DE being Budgie, 8GB RAM, an internet connection, enough storage and i5 8400T. If GPU matters, I'm using System76's driver. 1050M
## Additional context
with --scan is this: 
~/client$ gradle --scan
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/constanting/client/buildSrc/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':buildSrc'.
> Could not find method metadataSources() for arguments [build_1673jxpta96dip9rma4otezfs$_run_closure1$_closure6$_closure7@7c4f3b9b] on object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by TheKodeToad** [comment]
Please join Discord for support (seems you have an account anyway)! [Nice blue text which shall take you there.](https://discord.gg/TSAkhgXNbK)
