### ISSUE TITLE
Unable to change mod options

### ISSUE THREAD

**Issue by lv37** [Sol-Client/Client#144]
## Describe the bug
Sol doesn't create `.minecraft/config/sol-client/mods.json` which makes it impossible to edit mod configuration

## Steps to Reproduce
1. Install Sol for the first time
2. Edit mods
3. relaunch
4. config not saved

## Expected behavior
`.minecraft/config/sol-client/mods.json` should be checked and created at startup

## Environment
Fedora Linux, Sol client 2.0.0

## Additional context
Same problem for `.minecraft/config/sol-client/chat-filter.txt`

**Comment by TheKodeToad** [comment]
I knew about this, but thanks for reminding me! :P
