### ISSUE TITLE
Add a section selector in the mods screen 

### ISSUE THREAD

**Issue by TinLite** [Sol-Client/client#36]
As the title say, add a section selector in the mods screen. When you click a section title, it will jump right to the beginning of that mod section.

I mean, no one wants to scroll all the way down just to find the "Motion blur" option no?

**Comment by TinLite** [comment]
Nvm just found that there is a search bar in the corner of the screen. I'm dum

**Comment by TheKodeToad** [comment]
This is still a good idea.

**Comment by TheKodeToad** [comment]
I don't think it's needed now sections can be collapsed
