### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by biffotmc** [Sol-Client/Client#37]
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
5 actionable tasks: 3 executed, 2 up-to-date

**Comment by TheKodeToad** [comment]
I need to see the full output to know what's going on.

**Comment by biffotmc** [comment]
I have fixed the issue: I had tried to change the default keybind for freelook to be left alt but it didnt work and caused an error.

Is there a way to do this?

**Comment by TheKodeToad** [comment]
Did you change it in the code, or in controls.

**Comment by biffotmc** [comment]
how would i change it in the code because it didnt work for me ?

**Comment by TheKodeToad** [comment]
Do you agree that you will keep your version's code available (if you share it)? I've already had three people creating there own forks of this project, and I'm not against that, I just don't want people to take without credit.

I will give you a solution once you have agreed.

**Comment by biffotmc** [comment]
do i have to keep everything public or just the bits i use from your client?

**Comment by TheKodeToad** [comment]
You have to keep everything public. It's sort of a side-effect of using Replay Mod - Replay Mod requires that everything that uses it has public source code and also inherits that requirement.

While I could have removed Replay Mod and kept the old MIT license, I prefer GPL and it is used by many projects including the Linux kernel.

Anyway, one of the main purposes of this project was to create an open source Minecraft client, I don't want my code to be taken and used in closed source projects. Some of the code I used isn't even owned by me.

I don't really understand the point of making a Minecraft mod closed source - if you look at many of the best Minecraft mods, most (but not all) of them are open source - e.g. WorldEdit, Bukkit, Paper, Spigot, Quark, Forge, Fabric etc... (I don't want to be here all day).

If you make a Minecraft client closed source, people are less likely to trust it as as far as they know it will infect there computer with a RAT.

**Comment by biffotmc** [comment]
okay i’ll keep the source open if i release it

**Comment by TheKodeToad** [comment]
Also, give credit. Thank you!

You need to change:
```java
private KeyBinding key = new KeyBinding("Freelook", Keyboard.KEY_V, "Sol Client");
```
to
```java
private KeyBinding key = new KeyBinding("Freelook", Keyboard.LMENU, "Sol Client");
```

Good luck, have fun!
