### ISSUE TITLE
Can't tab out on Linux with mutliple monitors

### ISSUE THREAD

**Issue by JakeDevs** [Sol-Client/Client#38]
On popos you can't tab out unless you press f11 to put it into windowed mode or disable fullscreen in the settings. This happens on badlion, lunar, and sol and also vanilla.

Edit: I should also add this only happens on 1.8

Edit 2: I realized it only happens when you have dual monitors as well.

**Comment by TheKodeToad** [comment]
Does it happen on vanilla 1.8.9, or are you referring to vanilla 1.18.1?

**Comment by JakeDevs** [comment]
> 

nope, doesnt happen on vanilla and also doesnt happen on newer versions of minecraft.

**Comment by TheKodeToad** [comment]
I have issues on a single monitor too (yeah, I'm the biggest alt-tabber out there). Only, it does allow me to tab out.

https://user-images.githubusercontent.com/57493648/151156076-c963c153-aebf-4c19-9933-f5fcd67f2bfa.mp4

The problem seems to be that 1.13 uses LWJGL 3 while 1.8 uses the legacy LWJGL 2. LWJGL 2 has many issues on Linux and Mac including with fullscreen.

Somebody did port 1.8 to LWJGL (https://www.youtube.com/watch?v=uijUFzF-R7c), but it didn't look easy.

Alternatively, I could add the borderless fullscreen mod.

**Comment by JakeDevs** [comment]
> I have issues on a single monitor too (yeah, I'm the biggest alt-tabber out there). Only, it does allow me to tab out.
> fullscreen-2022-01-26_11.30.41.mp4
> 
> The problem seems to be that 1.13 uses LWJGL 3 while 1.8 uses the legacy LWJGL 2. LWJGL 2 has many issues on Linux and Mac including with fullscreen.
> 
> Somebody did port 1.8 to LWJGL (https://www.youtube.com/watch?v=uijUFzF-R7c), but it didn't look easy.
> 
> Alternatively, I could add the borderless fullscreen mod.

the borderless fullscreen option just doesnt work and doesnt fix the alt tab issue, at least in lunar.

**Comment by TheKodeToad** [comment]
> > I have issues on a single monitor too (yeah, I'm the biggest alt-tabber out there). Only, it does allow me to tab out.
> > fullscreen-2022-01-26_11.30.41.mp4
> > The problem seems to be that 1.13 uses LWJGL 3 while 1.8 uses the legacy LWJGL 2. LWJGL 2 has many issues on Linux and Mac including with fullscreen.
> > Somebody did port 1.8 to LWJGL (https://www.youtube.com/watch?v=uijUFzF-R7c), but it didn't look easy.
> > Alternatively, I could add the borderless fullscreen mod.
> 
> the borderless fullscreen option just doesnt work and doesnt fix the alt tab issue, at least in lunar.

Unfortunately, that just leaves using LWJGL 3, and it's not exactly an easy update.

It would be much easier if I could just edit Minecraft's source code, but with the new system it's not so simple.

I found https://github.com/grum/lwjglx, but it's really outdated and also too strictly licensed.

**Comment by JakeDevs** [comment]
> > > I have issues on a single monitor too (yeah, I'm the biggest alt-tabber out there). Only, it does allow me to tab out.
> > > fullscreen-2022-01-26_11.30.41.mp4
> > > The problem seems to be that 1.13 uses LWJGL 3 while 1.8 uses the legacy LWJGL 2. LWJGL 2 has many issues on Linux and Mac including with fullscreen.
> > > Somebody did port 1.8 to LWJGL (https://www.youtube.com/watch?v=uijUFzF-R7c), but it didn't look easy.
> > > Alternatively, I could add the borderless fullscreen mod.
> > 
> > 
> > the borderless fullscreen option just doesnt work and doesnt fix the alt tab issue, at least in lunar.
> 
> Unfortunately, that just leaves using LWJGL 3, and it's not exactly an easy update.
> 
> It would be much easier if I could just edit Minecraft's source code, but with the new system it's not so simple.
> 
> I found https://github.com/grum/lwjglx, but it's really outdated and doesn't have a proper license.

hi, you could do this but im pretty sure its a bug with gnome because it doesnt happen on kde plasma

**Comment by TheKodeToad** [comment]
> > > > I have issues on a single monitor too (yeah, I'm the biggest alt-tabber out there). Only, it does allow me to tab out.
> > > > fullscreen-2022-01-26_11.30.41.mp4
> > > > The problem seems to be that 1.13 uses LWJGL 3 while 1.8 uses the legacy LWJGL 2. LWJGL 2 has many issues on Linux and Mac including with fullscreen.
> > > > Somebody did port 1.8 to LWJGL (https://www.youtube.com/watch?v=uijUFzF-R7c), but it didn't look easy.
> > > > Alternatively, I could add the borderless fullscreen mod.
> > > 
> > > 
> > > the borderless fullscreen option just doesnt work and doesnt fix the alt tab issue, at least in lunar.
> > 
> > 
> > Unfortunately, that just leaves using LWJGL 3, and it's not exactly an easy update.
> > It would be much easier if I could just edit Minecraft's source code, but with the new system it's not so simple.
> > I found https://github.com/grum/lwjglx, but it's really outdated and doesn't have a proper license.
> 
> hi, you could do this but im pretty sure its a bug with gnome because it doesnt happen on kde plasma

You are correct that it doesn't happen on Plasma (as I found out in the single day of my life that I tried to use KDE Neon), but I'd still like to fix this as I prefer GNOME in its current state.

I don't think it's a bug with GNOME, because other applications don't mind if they are in fullscreen.

**Comment by TheKodeToad** [comment]
You can also do this:

![Screenshot from 2022-03-02 13-27-18](https://user-images.githubusercontent.com/57493648/156370647-bfbc25c6-ec75-44cc-8026-a3aa7656e9d5.png)

**Comment by TheKodeToad** [comment]
This *should* have been fixed with the introduction of borderless fullscreen.
