### ISSUE TITLE
Crash on first time

### ISSUE THREAD

**Issue by TeamBrave** [Sol-Client/Client#40]
## Description
I downloaded and installed Launcher for the first time. It crashed when I pressed the play button and I haven't been able to start it yet.
## Client Version
Running Sol Client v1.6.5 with OptiFine 1.8.9 HD U M5.
## Logs/Crash Report

[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/fifitowehu.txt)

**Comment by TheKodeToad** [comment]
This hasn't happened for anyone else.

**Comment by TeamBrave** [comment]
I'm using official [1.6.5](https://github.com/Sol-Client/Client/releases/tag/1.6.5) version.

**Comment by TheKodeToad** [comment]
I cannot reproduce this myself. Try reinstalling.

**Comment by TeamBrave** [comment]
I completely uninstalled and redownloaded it now. And it still crashes.
[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/ogufukuzus.txt)
https://prnt.sc/nL23QTeHcKY_

**Comment by TheKodeToad** [comment]
I honestly don't know what's going on.

**Comment by TheKodeToad** [comment]
Must be related to your locale. It seems that InWeb is being changed �nWeb.

**Comment by TheKodeToad** [comment]
It's something to do with your locale. After digging around, I found that Mixin (the other project we use for modifying the game) has trouble with non-English languages. Don't know how it took them so long for them to fix that, but we are using an old version to maintain compatibility with 1.8.

**Comment by TheKodeToad** [comment]
I've fixed it in the next version. It will auto update next time the client is opened. It's a better solution than changing your system language to English.
