### ISSUE TITLE
Short Description

### ISSUE THREAD

**Issue by cubecraftgames** [Sol-Client/client#45]
## Description
A description of the problem that is occurring.
## Steps to Reproduce
1. What did you do...
2. ...to crash the game?
## Client Version
Running Sol Client v1.7.4 with OptiFine 1.8.9 HD U M5.
## Logs/Crash Report

[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/ajokuciyec.txt)

**Comment by EinfxchJakob** [comment]
Umm?

**Comment by Pixelwarp** [comment]
You probs have a outdated graphics card so please update it

**Comment by TheKodeToad** [comment]
This is old, but asking on our Discord at https://discord.gg/TSAkhgXNbK is best.
