### ISSUE TITLE
Unable to build game with gradle on arm

### ISSUE THREAD

**Issue by KadTheAad** [Sol-Client/Client#46]
➜  ./gradlew build
Download https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/1.13.4/build-scan-plugin-1.13.4.pom
Download https://repo.spongepowered.org/maven/com/gradle/build-scan-plugin/1.13.4/build-scan-plugin-1.13.4.jar

> Configure project :
WARNING: You are using an unsupported version of ForgeGradle.
Please consider upgrading to ForgeGradle 5 and helping in the efforts to get old versions working on the modern toolchain.
See https://gist.github.com/TheCurle/fe7ad3ede188cbdd15c235cc75d52d4a for more info on contributing.
Version string 'unspecified' does not match SemVer specification 
You should try SemVer : http://semver.org/

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.logisticscraft:occlusionculling:0.0.5-SNAPSHOT.
  Searched in the following locations:
    - https://maven.minecraftforge.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://maven.minecraftforge.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://maven.minecraftforge.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - https://repo.maven.apache.org/maven2/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://repo.maven.apache.org/maven2/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://repo.maven.apache.org/maven2/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - https://libraries.minecraft.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://libraries.minecraft.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://libraries.minecraft.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - https://repo.maven.apache.org/maven2/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://repo.maven.apache.org/maven2/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://repo.maven.apache.org/maven2/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - https://libraries.minecraft.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://libraries.minecraft.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://libraries.minecraft.net/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - https://repo.spongepowered.org/maven/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://repo.spongepowered.org/maven/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://repo.spongepowered.org/maven/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - https://repo.codemc.io/repository/maven-public/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://repo.codemc.io/repository/maven-public/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://repo.codemc.io/repository/maven-public/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - https://repo.hypixel.net/repository/Hypixel/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://repo.hypixel.net/repository/Hypixel/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://repo.hypixel.net/repository/Hypixel/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - https://jitpack.io/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - https://jitpack.io/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - https://jitpack.io/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - file:/Users/myuser/.gradle/caches/minecraft/deobfedDeps/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/maven-metadata.xml
    - file:/Users/myuser/.gradle/caches/minecraft/deobfedDeps/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.pom
    - file:/Users/myuser/.gradle/caches/minecraft/deobfedDeps/com/logisticscraft/occlusionculling/0.0.5-SNAPSHOT/occlusionculling-0.0.5-SNAPSHOT.jar
    - file:/Users/myuser/.gradle/caches/minecraft/net/minecraft/minecraft/1.8.9/stable/22/occlusionculling-0.0.5-SNAPSHOT.jar
    - file:/Users/myuser/.gradle/caches/minecraft/net/minecraft/minecraft/1.8.9/stable/22/occlusionculling.jar
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 0s
5 actionable tasks: 3 executed, 2 up-to-date

**Comment by TheKodeToad** [comment]
I don't think this is an arm-related issue.

**Comment by TheKodeToad** [comment]
It seems to be fixed by running it multiple times

**Comment by TheKodeToad** [comment]
It should be fixed on the main branch.
