### ISSUE TITLE
Short Description

### ISSUE THREAD

**Issue by Akeush** [Sol-Client/Client#48]
## Description
A description of the problem that is occurring.
## Steps to Reproduce
1. What did you do...
2. ...to crash the game?
## Client Version
Running Sol Client v1.7.5 with OptiFine 1.8.9 HD U M5.
## Logs/Crash Report

[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/hutatohovo.txt)

**Comment by TheKodeToad** [comment]
Have you built it yourself?
