### ISSUE TITLE
Bossbar resizing

### ISSUE THREAD

**Issue by PottuGD** [Sol-Client/client#50]
Could you add scoreboard resizing to the scoreboard mod and bossbar resizing. I would really appreciate that. Otherwise really cool client.

**Comment by TheKodeToad** [comment]
Scoreboard is done.

**Comment by TheKodeToad** [comment]
The bossbar isn't.

**Comment by PottuGD** [comment]
Ok sorry

**Comment by TheKodeToad** [comment]
This is now possible (in unstable version)!
