### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Zetvue** [Sol-Client/client#52]
## Description
Crashes when starting up.
## Steps to Reproduce
1. Boot the game
## Client Version
Running Sol Client v1.7.5 with OptiFine 1.8.9 HD U M5.
## Logs/Crash Report

[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/gukepigive.txt)

**Comment by TheKodeToad** [comment]
😳 
The crash report is gone now.

**Comment by TheKodeToad** [comment]
Should've closed this earlier. Sadly I can't help now that it's exprired, sorry. Hopefully we can move to mclo.gs.
