### ISSUE TITLE
Cryptocurrency miner!

### ISSUE THREAD

**Issue by Piotersky** [Sol-Client/Client#53]
Really ... **Is there a cryptocurrency miner in that?** This npm  js library is for cryptocurrency mining!
**I hope you saw it before clicking launch, if not then uninstall it as soon as possible!!!**
![Mam koparkę](https://user-images.githubusercontent.com/97469920/168335861-8e1f4597-0d55-4d82-8455-95af535a904e.PNG)

**Comment by LynithDev** [comment]
No this generates cryptographic text.

**Comment by qewer33** [comment]
I hope this is a troll lmao

**Comment by TonehDev** [comment]
no way Sol Client has just been exposed for crypto miner! 🧐

**Comment by Piotersky** [comment]
> No this generates cryptographic text.
> 
> See [the official NodeJS documentation](https://nodejs.org/api/crypto.html)

Bruh I'm stupid... never mind

**Comment by Jenis7** [comment]
I hope this is a joke

**Comment by TheKodeToad** [comment]
Funny thing is I predicted this a few months ago.
