### ISSUE TITLE
Prism Launcher/MultiMC support

### ISSUE THREAD

**Issue by ajhfsdh** [Sol-Client/Client#54]
Seeing as this client is open source and community driven unlike other clients, is supporting 3rd part clients like Prism Launcher or MultiMC being considered?

**Comment by TheKodeToad** [comment]
Yeah, working on an installer

**Comment by ajhfsdh** [comment]
Sounds great, but how would this work for linux? We don't use the installer there.

**Comment by TheKodeToad** [comment]
This feature is literally being written on Linux

**Comment by TheKodeToad** [comment]
It does work but it's in progress.
