### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by zsak1** [Sol-Client/Client#61]
C:\Users\textr\Desktop\Client-1.8.1>npm install
ERROR: npm is known not to run on Node.js v12.3.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/

hey how do i fix it?

**Comment by TheKodeToad** [comment]
Download and install the latest NPM.

**Comment by EinfxchJakob** [comment]
npm install npm@latest -g

**Comment by zsak1** [comment]
https://www.toptal.com/developers/hastebin/efavaxayag.apache

**Comment by zsak1** [comment]
good works thanks for your help
and I have a question in the sol client launcher folder should be the app-1.8.1 folder?

**Comment by TheKodeToad** [comment]
Install git too.

**Comment by TheKodeToad** [comment]
Please ask on our Discord at https://discord.gg/TSAkhgXNbK if you want more help. Considering this issue was invalid to begin with, I'll close it.
