### ISSUE TITLE
Short Description

### ISSUE THREAD

**Issue by notdark25** [Sol-Client/Client#62]
## Description
A description of the problem that is occurring.
## Steps to Reproduce
1. What did you do...
2. ...to crash the game?
## Client Version
Running Sol Client v1.8.1 with OptiFine 1.8.9 HD U M5.
## Logs/Crash Report

[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/emudaduzex.txt)

**Comment by TheKodeToad** [comment]
Looks like a graphics driver issue.
