### ISSUE TITLE
Don't move inventory when potion effects are active

### ISSUE THREAD

**Issue by vytskalt** [Sol-Client/Client#63]
There is this annoying feature in 1.8 where if you have an active potion effect your inventory is moved to the side. It would be great if there was a setting to disable this. Patcher has added a fix for this, you can "borrow" some code from them: https://github.com/Sk1erLLC/Patcher/blob/master/src/main/java/club/sk1er/patcher/asm/render/screen/InventoryEffectRendererTransformer.java

**Comment by vytskalt** [comment]
Close this?

**Comment by TheKodeToad** [comment]
Yes.
I forgot.
