### ISSUE TITLE
Disable FPS animation

### ISSUE THREAD

**Issue by Aetopia** [Sol-Client/Client#66]
It seems the FPS Mod, updates at realtime which doesn't feel `normal`. Most clients + the FPS display in optifine tend to have some delay while updating FPS numbers. If possible consider to add a delay to the update.

**Comment by TheKodeToad** [comment]
It does have a delay, just with an animation.

**Comment by Aetopia** [comment]
I am not sure but most Clients and the optifine fps display tend to snap to values instead of going through an animation.

**Comment by senxd** [comment]
Isn't the delay like the counter for a second or something

**Comment by TheKodeToad** [comment]
This has been added as an option in main.
