### ISSUE TITLE
Raw Input

### ISSUE THREAD

**Issue by usergamma** [Sol-Client/client#67]
Please add Raw Mouse Input as in 1.13+. There is this mod (https://github.com/xCuri0/RawInputMod), but it doesn't work, and its forks only work for Windows. As far as I know no client has this.

**Comment by TheKodeToad** [comment]
It seems that you need permission to read the data in Linux.

**Comment by RaptaG** [comment]
Sol Client on root wen /j

**Comment by moehreag** [comment]
it might suffice for this to remove the additional calculations Minecraft does with the mouse position

**Comment by TheKodeToad** [comment]
It is possible to obtain elevated permissions graphically using `pkexec`. I don't know what you could do from there though.
