### ISSUE TITLE
Add cosmetics

### ISSUE THREAD

**Issue by avadhoot2008** [Sol-Client/Client#68]
I will help with the textures of cosmetics. @TheKodeToad

**Comment by TheKodeToad** [comment]
No need to mention me. I'd be happy for some new textures, but this client already has capes, just not paid ones.

People ask about cosmetics a lot, but I'd rather focus on more useful features. You can search on the Discord server for my previous responses.

**Comment by avadhoot2008** [comment]
where in your discord?

**Comment by TheKodeToad** [comment]
There are several responses I have given. Just search "cosmetics".
If you would like to contribute textures for capes, open a ticket.

**Comment by avadhoot2008** [comment]
Ok tysm

**Comment by VytskaLT** [comment]
If you ever add paid cosmetics please add an option for disabling them

**Comment by TheKodeToad** [comment]
> If you ever add paid cosmetics please add an option for disabling them

Yes, I will.
I won't add them anyway - if I ever want a bit of money donations would probably work just a well.
