### ISSUE TITLE
Short Description

### ISSUE THREAD

**Issue by JohnLoll** [Sol-Client/Client#70]
## Description
game immediately crashed after launch
## Steps to Reproduce
1. What did you do...
2. ...to crash the game?
## Client Version
Running Sol Client v1.8.2.
## Logs/Crash Report

[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/ibeserugaz.txt)

**Comment by TheKodeToad** [comment]
OptiFine is currently broken on mac (including the official version).
