### ISSUE TITLE
Improve fps

### ISSUE THREAD

**Issue by avadhoot2008** [Sol-Client/client#72]
The client gives barely 60fps whereas the other clients like lunar and feather gives me over 100fps.I have the same settings in all the the clients I mentioned above

**Comment by TheKodeToad** [comment]
Do you have vsync or max FPS on?

**Comment by avadhoot2008** [comment]
you can use the performance features from [https://github.com/Sk1erLLC/Patcher]

**Comment by TheKodeToad** [comment]
I tried Lunar Client and got pretty much the same average FPS (slightly lower) in the same Hypixel lobby with pretty much the same settings.

**Comment by avadhoot2008** [comment]
Then why does mine lack?

**Comment by TheKodeToad** [comment]
Maybe it is possible to improve it at least a bit. I just don't want to copy straight off another mod.

I forgot to close earlier, but this is a duplicate of #30.
