### ISSUE TITLE
Add mutiversion

### ISSUE THREAD

**Issue by avadhoot2008** [Sol-Client/Client#75]
we can use the [helios launcher code](https://github.com/dscalzi/HeliosLauncher) to add multiversion

**Comment by avadhoot2008** [comment]
This can include choice of versions between 1.7 , 1.8 , 1.12 , 1.14 , 1.16 , 1.18 and the latest version 1.19

**Comment by TheKodeToad** [comment]
This is already a planned feature. See #41, and #8. Sorry for closing most of your issues, it's just easier to track progress if there are no duplicates.
