### ISSUE TITLE
Calculating Smooth Scroll on Tick instead of Render

### ISSUE THREAD

**Issue by DarkKronicle** [Sol-Client/Client#76]
https://github.com/Sol-Client/Client/blob/5a6956c3cff0038dbfdbac47c83afdcc9b4e2f0b/game/src/main/java/io/github/solclient/client/ui/component/impl/ScrollListComponent.java#L243=

Calculating smooth scroll on tick creates a bit of a jarring feeling since it only updates 20 times a second, when menu FPS can be significantly higher. To fix this, you can just move it into the render method. 

I have it implemented like this in [DarkKore](https://github.com/DarkKronicle/DarkKore/blob/main/src/main/java/io/github/darkkronicle/darkkore/gui/components/transform/ScrollComponent.java#L69=)

**Comment by TheKodeToad** [comment]
It's already lerped in the render method, so it basically feels like 60 FPS. This is the method used by OK Zoomer for the zoom scrolling.

**Comment by DarkKronicle** [comment]
Oop didn't see that. I think I just had some FPS drops.
