### ISSUE TITLE
Lag renders resource pack selection screen unusable 

### ISSUE THREAD

**Issue by AidanLCB** [Sol-Client/client#78]
## Describe the bug
Immense lag on the resource packs selection screen. 

## Steps to Reproduce
For me it is as simple as going to the packs screen. It may be worth noting that I have around 2.7gb of texture packs, with many nested folders, and with some of the packs unzipped as for a while my pc had trouble compressing files for some reason. 

## Expected behavior
I expect to be able to smoothly scroll and select my resource packs, instead of having to wait 10 seconds or so just to scroll one notch. 

## Environment
Windows 11, with optifine

**Comment by TheKodeToad** [comment]
Does this happen in vanilla too?

**Comment by AidanLCB** [comment]
in vanilla it is fine, however most of my packs don't load as i use folders to organize many of them

**Comment by mkdrch** [comment]
i have same issue

**Comment by TheKodeToad** [comment]
I know what's causing it now.
