### ISSUE TITLE
i did nothing

### ISSUE THREAD

**Issue by yukkyhere** [Sol-Client/client#83]
## Description
A description of the problem that is occurring.
## Steps to Reproduce
1. What did you do...
2. ...to crash the game?
## Client Version
Running Sol Client v1.8.2 with OptiFine 1.8.9 HD U M5.
## Logs/Crash Report

[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/paquhagoze.txt)

**Comment by yukkyhere** [comment]
1 i did lag machine

**Comment by TheKodeToad** [comment]
What's the contents of your configuration file (%APPDATA%/Sol Client/minecraft/sol_client_mods.json).

**Comment by TheKodeToad** [comment]
I have no idea how this could happen, but this issue *should* be fixed in `develop`.
