### ISSUE TITLE
Unable to compile game

### ISSUE THREAD

**Issue by PhantomTimed** [Sol-Client/Client#90]
## Describe the bug
The game is not compiling properly

## Steps to Reproduce
1. Download source
2. Setup (npm i)
3. Run npm buildGame
4. This also leads to another issue on windows, it gives the error The system cannot find the file specified
5. Get error

## Expected behavior
The game to compile and to be used with the launcher

## Environment
Windows 11 HP Z800 Workstation (yes i still use these) Java JDK 8, no JRE and gradle 7.5.1 installed

**Comment by TheKodeToad** [comment]
I need the full error message to help. If you can't work out how to copy it in CMD, just send a screenshot. You can do so by dragging it into the textarea.

Also, this isn't really a bug. This is more an issue on your side, so I'd prefer to use Discord or GitHub Discussions in future.

**Comment by TheKodeToad** [comment]
You need to do `gradlew` instead of `gradle` - `gradle` uses the system installation.

**Comment by TheKodeToad** [comment]
Try using Java 8.

**Comment by PhantomTimed** [comment]
![image](https://user-images.githubusercontent.com/108957552/187020277-b0186bda-11a0-4495-aebc-408bcd1a34c8.png)
I have java 8 though.

**Comment by TheKodeToad** [comment]
Make sure JAVA_HOME corresponds to correct folder. I don't know how to set environment variables on Windows, but that's what you need to do.

**Comment by PhantomTimed** [comment]
You simply just search up Environment Variables, i'll try that.

**Comment by PhantomTimed** [comment]
Wait, there is no JAVA_HOME variable?

**Comment by PhantomTimed** [comment]
I'll try uninstalling then reinstalling java, also I did make a bug report about this on the gradle github page and i resolved it somehow. I'll go check

**Comment by TheKodeToad** [comment]
I wouldn't recommend reporting issues for things that aren't the fault of the developers. They will get closed on most repositories (I would have moved this to a GitHub discussion if I knew how).
Gradle is not going to support the ancient version (which is being updated soon) we use either.

**Comment by PhantomTimed** [comment]
Yes, I am able to join the server.

**Comment by TheKodeToad** [comment]
It seems you are already on the server.
You can ask in #ProgrammingTalk or #community-support.

**Comment by PhantomTimed** [comment]
This has been fixed, just so everyone else knows. It's problems with environment variables
