### ISSUE TITLE
Command Line Launcher?

### ISSUE THREAD

**Issue by GameParrot** [Sol-Client/client#91]
## Problem
It would be nice to have an option to launch the game from the command line.

## Solution
A separate executable could have command-line arguments that allow for launching the game via Terminal without showing the Launcher window.

## Alternative Solutions
The main executable could have command-line arguments that allow for launching from Terminal (may also show the launcher window)

**Comment by TheKodeToad** [comment]
If this is implemented, it will most likely be in the new (currently unfinished) [launcher](https://github.com/Sol-Client/Launcher).

**Comment by artdeell** [comment]
Also, you can use the Installer, and then use any command line launcher of your liking (if it support Mojang .json format or PolyMC instances)

**Comment by TheKodeToad** [comment]
Since merge of #123 this can no longer be considered.
