### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by ZebastianJV** [Sol-Client/client#97]
## Description (please fill in)
I mean it's self-explanatory, it crashes when I join a server.
## Steps to Reproduce
1. Went to a Multiplayer server (Hypixel)
2. After it saying "Logging in", it crashes
## Details
Running Sol Client v1.8.6 with OptiFine 1.8.9 HD U M5 on Windows.
## Logs/Crash Report
[crash.txt](https://github.com/Sol-Client/Client/files/9632296/crash.txt)

## Video link:
https://streamable.com/wbnhdc

Keep in mind that this is my first time launching this cause I wanna try out the client.

**Comment by artdeell** [comment]
Looks like an Intel graphics driver bug

**Comment by TheKodeToad** [comment]
A lot of people seemed to had this issue, but it looks like a graphics problem - not one with the client.

**Comment by TheKodeToad** [comment]
Have you tried deleting options.txt?
In %APPDATA%/Sol Client/minecraft.

**Comment by ZebastianJV** [comment]
> Have you tried deleting options.txt? In %APPDATA%/Sol Client/minecraft.
na I havent yet, I used my D: drive to store my .minecraft folder so yeah.

**Comment by ZebastianJV** [comment]
> A lot of people seemed to have had this issue, but it looks like a graphics problem - not one with the client.

how would it be? I know my Intergrated graphics is old but at least lunar can handle it. Its in the latest driver (2021 i think)

**Comment by ZebastianJV** [comment]
> Have you tried deleting options.txt? In %APPDATA%/Sol Client/minecraft.

alright, i tried deleting but still the same issue. My options did reset tho.

**Comment by TheKodeToad** [comment]
> > A lot of people seemed to have had this issue, but it looks like a graphics problem - not one with the client.
> 
> how would it be? I know my Integrated graphics is old but at least lunar can handle it. It's in the latest driver (2021 I think) Plus, it works with vanilla or any other client except this client.

This client doesn't have any particularly fancy graphics - it can run on phones with PojavLauncher so I am quite puzzled by this.

**Comment by ZebastianJV** [comment]
> > > A lot of people seemed to have had this issue, but it looks like a graphics problem - not one with the client.
> > 
> > 
> > how would it be? I know my Integrated graphics is old but at least lunar can handle it. It's in the latest driver (2021 I think) Plus, it works with vanilla or any other client except this client.
> 
> This client doesn't have any particularly fancy graphics - it can run on phones with PojavLauncher so I am quite puzzled by this.

I really do wanna try this out tho, I guess it just doesn"t like it.

**Comment by TheKodeToad** [comment]
It's probably a problem with the launcher.
Try installer it with https://github.com/Sol-Client/Installer/releases/download/dev-4/Sol-Client-Installer.jar.

**Comment by ZebastianJV** [comment]
> It's probably a problem with the launcher. Try installing it with https://github.com/Sol-Client/Installer/releases/download/dev-4/Sol-Client-Installer.jar.
![2022-09-23_11-00](https://user-images.githubusercontent.com/75558359/191884815-e92e5d9e-56ed-4231-8170-38eea484593a.png)
it failed for me (thru polymc and Minecraft launcher)

**Comment by ZebastianJV** [comment]
> It's probably a problem with the launcher. Try installing it with https://github.com/Sol-Client/Installer/releases/download/dev-4/Sol-Client-Installer.jar.

If it did work, what location do I use cause searching up Sol client on minecraft and polymc launcher using default directories, they don't show up in the versions list or as a profile for me when it failed.

**Comment by ZebastianJV** [comment]
I checked the versions list, and it doesn't have any files at all.
![image](https://user-images.githubusercontent.com/75558359/191885203-193119c0-fbcd-4a9a-a111-440e43d5caf3.png)

**Comment by TheKodeToad** [comment]
> > It's probably a problem with the launcher. Try installing it with https://github.com/Sol-Client/Installer/releases/download/dev-4/Sol-Client-Installer.jar.
> > ![2022-09-23_11-00](https://user-images.githubusercontent.com/75558359/191884815-e92e5d9e-56ed-4231-8170-38eea484593a.png)
> > it failed for me (thru polymc and Minecraft launcher)

Maybe try again.
Looks like an internet issue.

**Comment by ZebastianJV** [comment]
> > > It's probably a problem with the launcher. Try installing it with https://github.com/Sol-Client/Installer/releases/download/dev-4/Sol-Client-Installer.jar.
> > > ![2022-09-23_11-00](https://user-images.githubusercontent.com/75558359/191884815-e92e5d9e-56ed-4231-8170-38eea484593a.png)
> > > it failed for me (thru polymc and Minecraft launcher)
> 
> Maybe try again. Looks like an internet issue.

![image](https://user-images.githubusercontent.com/75558359/191936961-be0ab818-4260-43b5-9a11-afa33e755177.png)

![image](https://user-images.githubusercontent.com/75558359/191937526-1f21ccc7-bafa-408c-88ab-110deace16d9.png)
yo i did what you said and it didn't crash this time. However it went to a black screen. I could hear game sounds and when i press ESC it does put my cursor to the middle which means the game is working I just can't see anything. It also turns to a black screen before when it doesn't crash. I probably should've said that before but you know now.

**Comment by TheKodeToad** [comment]
Try disabling motion blur and menu blur.
If you need further support, send in [#community-support](https://discord.com/channels/886561982872977408/886652743937306634).

**Comment by ZebastianJV** [comment]
> Try disabling motion blur and menu blur. If you need further support, send in [#community-support](https://discord.com/channels/886561982872977408/886652743937306634).

alright ill try that and update you.

EDIT: Turns out, I already had them disabled since I know it was going to reduce fps at least for me.
![image](https://user-images.githubusercontent.com/75558359/191938970-9d8d4655-f542-4f40-9ab0-bd61629aecad.png)

**Comment by TheKodeToad** [comment]
Colour saturation?

**Comment by ZebastianJV** [comment]
> Colour saturation?

![image](https://user-images.githubusercontent.com/75558359/191939587-e739cc73-5dc8-43c8-ba77-8b0646f7d8fc.png)
OMG I CAN'T BELIEVE THAT WAS THE CULPRIT.
Thanks for the fix it could be prob something to do with fast render being dumb or something but that fixed the issue. Thank you again!

**Comment by TheKodeToad** [comment]
This problem still exists with the launcher.

**Comment by ZebastianJV** [comment]
> This problem still exists with the launcher.

hmmm, ill try it on the launcher and see if its also doing it. And i'll update you on that.

**Comment by ZebastianJV** [comment]
There are also problems with the mouse sensitivity being kind of jank but that's prob my laptop since it always does it at first boot. However, it doesn't need to be this long to fix it.

**Comment by TheKodeToad** [comment]
There is nothing we can do due to #123 - considering it works in other launchers this is probably fixed.
